title: Project

files:
  sortable: true

pages:
  template: project

pages: false

fields:
  title:
    label: Title
    type:  text

  bgcolor:
    label: Background Color
    type:  color
    default: ffffff
    width: 1/4

  textcolor:
    label: Text Color
    type:  color
    default: 000000
    width: 1/4

  categories:
    label: Categories
    type: checkboxes
    options:
      design: Design
      illustration: Illustration
    width: 1/2

  text:
    label: Text
    type:  textarea